# Generated by Django 5.0 on 2023-12-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='fatherName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='graduation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='motherName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resume/'),
        ),
        migrations.AlterField(
            model_name='users',
            name='tenthMarks',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='twelvethMarks',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
