# Generated by Django 5.0 on 2023-12-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_studentconsent_consent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterinfo',
            name='lastDateToApply',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentconsent',
            name='consent',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
